
modeling-parameters:
  # Model parameters
  num_years: 82         # number of years to run the model
  timesteps_per_year: 0.05   # number of timesteps per year
  initFile: 'data/extended_beta1000yrs.h5' # input file
  paramsFile: 'data/extended_beta1000yrs.yaml' # parameter file
  meshFile: 'data/PigFull2017GeomFull.exp' # mesh file
  SMBFile: 'data/OLS_Trend_plus_Resid_9b9.tif' # SMB file
  #water_to_ice: 1.087241003            # density ratio of water to ice
  water_to_ice: 1.0872410032715376 
  water_density: 1028
  GLThresh: 41
  uThresh: 300
  hThresh: 30                        # minimum ice thickness required in a mesh element with ice (meters)
  tag: '001'
  experiments: 0                     # experiment 1 for changing timing of basal melt, 1 for changing C, 2 for ... 
  bmr_increase_time: 0               # timing (in years) of when to begin a linear increase in BMR (relative to start of simulation)
  #save_steps: [19, 34, 54, 69, 81]  # years into the simulation at which to save the flowline profile (for a simulation of PIG between 1935 - 2017)
  save_steps: [34, 69, 81]           # years into the simulation at which to save the flowline profile (OMIT SAVING THE INITIAL STATE that is saved manually)

enkf-parameters:
  # Ensemble Kalman Filter parameters
  #Nens: 40                 # number of ensemble members (now set in the command line)
  freq_obs: 1              # frequency of observations (per year?)
  obs_max_time: 40         # maximum time for observations
  obs_start_time: 10        # start time for observations
  random_field_method: graph   # graph or fft

  num_state_vars: 5      # number of state variables  [h ,u, v, s, bmr]
  num_param_vars: 0       # number of parameter variables [bmr]
  vec_inputs: ['h','u','v', 's', 'basal_melt_field']
  observed_params: ['s']  # surface elevation

  generate_synthetic_obs: 1  # Generate synthetic observations for testing
  generate_true_state:    1  # Generate true state for synthetic observations
  generate_nurged_state:  1  # Generate nudged state for synthetic observations
  initialize_ensemble: 1
  use_ensemble_pertubations: 1 # Use ensemble perturbations for ensemble state
  sequential_ensemble_initialization: 0  # Sequential ensemble initialization (True for sequential, False for parallel)

  # Statistical parameters (based on the number of state variables)
  sig_model: [0.1,0.1,0.1,0.1,0.1] # model error standard deviation
  sig_obs: [5,0.5,0.1,0.1,0.1]   # observation error standard deviation
  sig_Q: [0.8,0.4,0.01,0.08,0.1]    # process noise standard deviation
  length_scale: [96,96,90,80,80]   # length scale for the covariance matrix, can be a list

  seed: 1                 # seed for random number generator
  inflation_factor: 1.15          # inflation factor
  localization_flag: False      # localization flag: True, False

  # estimation flags
  joint_estimation: 0 # joint estimation flag: True, False
  parameter_estimation: False # parameter estimation flag: True, False
  joint_estimated_params: [] # parameter(s) to be jointly estimated

  # nudged parameters
  wrong_basal_melt_field: 5         # scalar factor to "nudge" the basal melt rate field

  # enkf model parameters
  model_name: "icepack"               # name of the model
  model_solver: "solver_weertman"     # name of the solver
  filter_type: "EnKF"               # name of the filter: EnKF, DEnKF, EnTKF, EnRSKF
  local_analysis: False           # local analysis flag: True, False, global analysis is default
  parallel_flag: "MPI_model"             # parallel flag: Serial, MPI, MPI_model
  n_modeltasks: 1                     # number of model tasks (for MPI)
  commandlinerun: "True"              # command line run flag: True, False
  execution_flag: 0                  #`execution flag: 0 ->default, 1 -> sequntial, 2 -> even_distribution_of_problem size, 3 -> even_distribution_of_problem size with load balancing
  execution_mode: 1                  # execution mode: 0 -> serial, 1 -> partial parallel_run, 2 -> fully parallel run
  data_path: _modelrun_datasets
 